### ISSUE TITLE
Difficulty using the effect_shift_log2(coef1, coef2) command

### ISSUE THREAD

**Issue by jpmam1** [pfh/topconfects#1]
Hi Paul,

I love the TopConfects package - it's brilliant!! 

My issue is with the ```effect_shift_log2()``` command: I don't understand what it means by 'coefs'. The documentation might be improved with an example (or maybe I'm just not getting it).

I've tried ```effect_shift_log2(c(group2), c(group3))``` & ```effect_shift_log2(c(1), c(2))``` with output: 

$signed
[1] TRUE

$limits
[1] -1  1

$df
[1] 1

$calc
function (beta) 
effect$calc(exp(beta * ln2))
<bytecode: 0x177e6e9f8>
<environment: 0x17ab32c60>

$constraint
function (effect_size) 
{
    cons <- effect$constraint(effect_size)
    function(beta) {
        e <- exp(beta * ln2)
        result <- cons(e)
        list(score = result$score, grad = ln2 * e * result$grad)
    }
}
<bytecode: 0x1812ba0b0>
<environment: 0x17ab32c60>

and I've also tried ```effect_shift_log2(c(1,2,3), c(4,5,6,7))``` (output: ```Error: length(coef1) not equal to length(coef2)```)

For my data I have 3 groups with uneven numbers:

efit$design

| Sample | (Intercept) | group2 | group3 |
|:---- |:-----:|:-----:|:-----:|
|1 |            1   |   0   |   0|
|2 |          1   |   0    |  0 |
|3 |           1    |  0   |   0 |
|4 |           1   |   1    |  0 |
|5 |           1    |  1   |   0 |
|6 |           1    |  1   |   0 |
|7 |           1    |  1   |   0 |
|8 |           1    |  0   |   1 |
|9 |           1    |  0   |   1 |
|10 |          1    |  0   |   1 |

Output from R:
> effect <- effect_shift_log2(c(1,2,3), c(8,9,10))
> nonlinear <- edger_confects(efit, effect=effect)
Error in addPriorCount(data$counts, offset = data$offset, prior.count = 0.125) : 
  requested row index out of range

Any help/advice you can provide on this would be very much appreciated.

Thanks,
Jared

**Comment by pfh** [comment]
Hi Jared,

coef1 and coef2 are two vectors of equal length, referring to coefficients by *column* number in the design matrix. This effect size is only going to be meaningful for the interaction of two experimental factors, and setting up the design matrix is a little unusual. Each coefficient has to represents the intersection of a level in one factor and a level in another, and there needs to be no intercept term.  There is an example here: http://logarithmic.net/topconfects/articles/nonlinear_effect.html

It's not applicable to your data, since it has only a single experimental factor. An effect size appropriate for a one-way ANOVA is something I've considered. Can look into this if you are interested.

**Comment by jpmam1** [comment]
Thank you for the quick response Paul.

As I suspected it was a user error (i.e. I was trying to make the package do something that doesn't 'make sense') and the example you've linked clearly shows how the command is supposed to be used. An effect size for a one-way ANOVA might be quite useful in specific situations, but for my current project it wouldn't be worth your time/effort; maybe something for a future version :)

Thanks,
Jared
