### ISSUE TITLE
confect score threshold

### ISSUE THREAD

**Issue by jonbra** [pfh/topconfects#6]
Hi,

I was wondering if it is possible to say something about what is a reasonable lower bound for the confect score, or if it is always up to the user to choose a reasonable level? 

Thanks, Jon

**Comment by pfh** [comment]
Hi Jon,

Any advice for choosing a TREAT threshold also applies to topconfects. Otherwise it's up to the user.

I would consider even zero a reasonable lower bound (non-significant genes get a score of NA).

Best to discuss this on the Bioconductor support site:
https://support.bioconductor.org/p/130595/
